services:
  # Backend API with SQLite
  - type: web
    name: metascope-backend
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./data.db
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO

  # Frontend React App
  - type: web
    name: metascope-frontend
    env: node
    plan: free
    region: singapore
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: metascope-backend
          property: host
