services:
  # PostgreSQL Database
  - type: pserv
    name: metascope-postgres
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: POSTGRES_DB
        value: taxi_catalog
      - key: POSTGRES_USER
        value: metascope_user
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Redis Cache
  - type: redis
    name: metascope-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Backend API
  - type: web
    name: metascope-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: metascope-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: metascope-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO

  # Frontend React App
  - type: static
    name: metascope-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: metascope-backend
          property: host

databases:
  - name: metascope-postgres
    databaseName: taxi_catalog
